// Fetch lists
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
